project:
  type: website
  output-dir: docs
website:
  title: "HananBlog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://hyafai.github.io/Hanan-Blog/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual